name: Daily Countdown to Discord

on:
  schedule:
    - cron: "0 16 * * *" # 12:00 AM GMT+8
  workflow_dispatch:

jobs:
  post-countdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm start:countdown
        env:
          DISCORD_WEBHOOK_URL_CD: ${{ secrets.DISCORD_WEBHOOK_URL_CD }}
