name: Daily Countdown to Discord

on:
  schedule:
    - cron: "0 16 * * *" # 12:00 AM GMT+8
  workflow_dispatch:

jobs:
  post-countdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npx ts-node scripts/countdown.ts
        env:
          DISCORD_WEBHOOK_URL_CD: ${{ secrets.DISCORD_WEBHOOK_URL_CD }}
